[project]
name = "libanswers_webapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "marimo>=0.13.7",
    "pandas>=2.2.3",
    "ruff>=0.11.9",
]
